### PR TITLE
Update zh_CN.po

### PR DESCRIPTION
**Pull request by eremiter**
Add some translation items and correct some redundant translations

## Description
<Info on what this pull request adds>
Add some translation items and correct some redundant translations

### Submitter Checklist

- [ ] Squashed commits with `git rebase -i` (if needed)
- [ ] Built budgie-control-center and verified that the patch worked (if needed)

### CODE REVIEW

**Comment by fossfreedom** [comment]
HI there - thanks for submitting this pull request.

All our translations are via transifex. We will pull the latest translations at release time. Please join and submit your changes via transifex.

https://www.transifex.com/buddiesofbudgie/budgie-control-center

thanks.

**Comment by eremiter** [comment]
Hello Sir,
1. What does budgie-10 mean? Does it mean version 10 or version 22.04.

2. https://explore.transifex.com/ubuntu-budgie/  I have reviewed all the translations, and I have also translated all the translations.
 The only thing missing is this one (budgie-10). Could you please open it for me to review.

3. What is the relationship between ubuntu-budgie and buddiesofbudgie, which master and which slave.
https://explore.transifex.com/buddiesofbudgie https://explore.transifex.com/ubuntu-budgie
4. my account: Tianyazi

Best regards,
 
From: David Mohammed
Date: 2022-11-03 21:10
To: BuddiesOfBudgie/budgie-control-center
CC: Budgie; Author
Subject: Re: [BuddiesOfBudgie/budgie-control-center] Update zh_CN.po (PR #42)
HI there - thanks for submitting this pull request.
All our translations are via transifex. We will pull the latest translations at release time. Please join and submit your changes via transifex.
https://www.transifex.com/buddiesofbudgie/budgie-control-center
thanks.

**Comment by eremiter** [comment]
Hello Sir,
1. What does budgie-10 mean? Does it mean version 10 or version 22.04.
Change the zh.po file to zh CN.po.

2. https://explore.transifex.com/ubuntu-budgie/  I have reviewed all the translations, and I have also translated all the translations.
 The only thing missing is this one (budgie-10). Could you please open it for me to review.

3. What is the relationship between ubuntu-budgie and buddiesofbudgie, which master and which slave.
https://explore.transifex.com/buddiesofbudgie https://explore.transifex.com/ubuntu-budgie
4. my account: Tianyazi

Best regards,
 
From: David Mohammed
Date: 2022-11-03 21:10
To: BuddiesOfBudgie/budgie-control-center
CC: Budgie; Author
Subject: Re: [BuddiesOfBudgie/budgie-control-center] Update zh_CN.po (PR #42)
HI there - thanks for submitting this pull request.
All our translations are via transifex. We will pull the latest translations at release time. Please join and submit your changes via transifex.
https://www.transifex.com/buddiesofbudgie/budgie-control-center
thanks.

**Comment by fossfreedom** [comment]
Budgie 10 is the version of budgie. Budgie 11 is the future budgie 

Buddies and Ubuntu Budgie are independent projects.

Buddies produce the desktop itself.   Ubuntu Budgie is one of the distros that ship budgie desktop

**Comment by fossfreedom** [comment]
I will look to rename zh to zh_CN next week. Thx.

**Comment by eremiter** [comment]
Dear David,

Thank you very much. Remember to upgrade my account and have the review authority.
My account:Tianyazi

Best regards,
 
From: David Mohammed
Date: 2022-11-06 22:23
To: BuddiesOfBudgie/budgie-control-center
CC: Budgie; Author
Subject: Re: [BuddiesOfBudgie/budgie-control-center] Update zh_CN.po (PR #42)
I will look to rename zh to zh_CN next week. Thx.

**Comment by eremiter** [comment]
Hello Sir,
1. https://www.transifex.com/buddiesofbudgie/budgie-10 
This needs to change the Chinese zh.po to zh CN.po, thank you
2. 
budgie-10,budgie-control-center,budgie-desktop-view,  Could you please increase the approval authority of my account? No one can review it at present, thank you.

Best regards,
 
From: David Mohammed
Date: 2022-11-06 22:23
To: BuddiesOfBudgie/budgie-control-center
CC: Budgie; Author
Subject: Re: [BuddiesOfBudgie/budgie-control-center] Update zh_CN.po (PR #42)
I will look to rename zh to zh_CN next week. Thx.
―

**Comment by JoshStrobl** [comment]
We are aware, please be patient. Many of us are busy.

**Comment by eremiter** [comment]
Hello Sir,

Sorry to bother you. I'm in no hurry.

Best regards,
 
From: Joshua Strobl
Date: 2022-11-09 15:22
To: BuddiesOfBudgie/budgie-control-center
CC: Budgie; Author
Subject: Re: [BuddiesOfBudgie/budgie-control-center] Update zh_CN.po (PR #42)
We are aware, please be patient. Many of us are busy.

**Pull request closed without merging**
